### ISSUE TITLE
Error: Not Found

### ISSUE THREAD

**Issue by samsam-ahmadi** [ntltd/release-generator#1]
Hey, I just try to use the release-generator as we have in this repository. but I got this error and I don't know why.

Here are the Details: 
https://github.com/samsam-ahmadi/github-actions/tree/main/.github

<img width="520" alt="Screen Shot 1399-12-29 at 15 03 47" src="https://user-images.githubusercontent.com/18388480/111774299-828a4780-88c4-11eb-9fce-50dac368106b.png">

**Comment by samsam-ahmadi** [comment]
Ohh, Sorry I changed the master branch to main and makes this problem.
now fixed.

**Comment by lawrencebensaid** [comment]
I'm getting this too.

I tried `main`, `master`, `v1.1.1`.
None of those work...

```yml
      - name: Generate release
        uses: ntltd/release-generator@v1.1.1
        with:
          releaseName: ${{ env.APP }} v${{ steps.package.outputs.version }}
          releaseTag: v${{ steps.package.outputs.tag }}
          templatePath: .github/release.md
          token: ${{ github.token }}
          draft: true
```
